[package]
name = "homepod-sink"
version = "0.1.0"
edition = "2021"

[dependencies]
airplay-client = { path = "/home/filedesless/src/airplay2-rs/crates/airplay-client" }
airplay-core = { path = "/home/filedesless/src/airplay2-rs/crates/airplay-core" }
airplay-audio = { path = "/home/filedesless/src/airplay2-rs/crates/airplay-audio" }

pipewire = { version = "0.10", features = ["v0_3_65"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
